In [1]:
import numpy as np
import pandas as pd

# List of 20 cuisine types
cuisines = [
    'Italian', 'American', 'Chinese'
    , 'Mexican', 'Indian', 'Japanese'
    , 'French', 'Thai', 'Spanish'
    , 'Mediterranean', 'Greek', 'Lebanese'
    , 'Turkish', 'Korean', 'Vietnamese'
    , 'Persian', 'Brazilian', 'Caribbean'
    , 'Moroccan', 'Ethiopian'
]

# Manually filling data for 20 customers
data = [
    [50, 0, 0, 0, 200, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],    # Customer 1
    [0, 0, 0, 300, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],   # Customer 2
    [0, 150, 0, 0, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],   # Customer 3
    [0, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0, 200, 0, 0, 0, 0, 0, 0, 0, 0],    # Customer 4
    [0, 0, 0, 200, 0, 0, 0, 0, 100, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0], # Customer 5
    [0, 0, 0, 0, 0, 100, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200, 0, 0], # Customer 6
    [0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0],    # Customer 7
    [0, 0, 0, 0, 0, 0, 0, 100, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0],   # Customer 8
    [0, 200, 0, 0, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0, 0, 0],  # Customer 9
    [0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 200, 0, 0, 0, 0, 0, 0, 0, 0, 0],   # Customer 10
    [0, 0, 0, 50, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],    # Customer 11
    [100, 0, 0, 0, 0, 0, 0, 0, 0, 200, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],   # Customer 12
    [0, 50, 0, 0, 200, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0, 0],  # Customer 13
    [0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0],    # Customer 14
    [0, 0, 0, 0, 100, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200, 0], # Customer 15
    [0, 0, 50, 0, 0, 0, 0, 100, 0, 0, 200, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # Customer 16
    [0, 0, 100, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],   # Customer 17
    [50, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0],  # Customer 18
    [0, 0, 100, 200, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 0, 0, 0],  # Customer 19
    [0, 0, 0, 0, 50, 0, 0, 0, 0, 200, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0],  # Customer 20
]

# Create DataFrame
data = pd.DataFrame(data, columns=cuisines)
# Display the dataset
data

,Italian,American,Chinese,Mexican,Indian,Japanese,French,Thai,Spanish,Mediterranean,Greek,Lebanese,Turkish,Korean,Vietnamese,Persian,Brazilian,Caribbean,Moroccan,Ethiopian
0,50,0,0,0,200,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,300,0,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,150,0,0,0,0,0,0,100,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,50,0,0,0,0,0,0,200,0,0,0,0,0,0,0,0
4,0,0,0,200,0,0,0,0,100,0,0,0,0,150,0,0,0,0,0,0
5,0,0,0,0,0,100,150,0,0,0,0,0,0,0,0,0,0,200,0,0
6,0,0,100,0,0,0,0,0,0,0,0,0,0,50,0,0,0,0,0,0
7,0,0,0,0,0,0,0,100,0,0,0,0,150,0,0,0,0,0,0,0
8,0,200,0,0,0,0,0,50,0,0,0,0,0,0,0,100,0,0,0,0
9,0,0,100,0,0,0,0,0,0,0,200,0,0,0,0,0,0,0,0,0
10,0,0,0,50,0,0,100,0,0,0,0,0,0,0,0,0,0,0,0,0
11,100,0,0,0,0,0,0,0,0,200,0,0,0,0,0,0,0,0,0,0
12,0,50,0,0,200,0,0,0,0,0,0,0,0,0,0,0,100,0,0,0
13,0,0,100,0,0,0,0,0,0,0,0,0,0,50,0,0,0,0,0,0
14,0,0,0,0,100,0,0,0,150,0,0,0,0,0,0,0,0,0,200,0
15,0,0,50,0,0,0,0,100,0,0,200,0,0,0,0,0,0,0,0,0
16,0,0,100,0,0,0,0,0,0,150,0,0,0,0,0,0,0,0,0,0
17,50,0,0,100,0,0,0,0,0,0,0,150,0,0,0,0,0,0,0,0
18,0,0,100,200,0,0,0,0,0,0,0,0,0,0,0,0,50,0,0,0
19,0,0,0,0,50,0,0,0,0,200,0,0,100,0,0,0,0,0,0,0

# NMF

In [2]:
from sklearn.decomposition import NMF
from sklearn.preprocessing import MinMaxScaler

# Preprocess the data (Standardize it)
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)

In [69]:
# Apply NMF to extract latent factors
nmf = NMF(n_components=5, init='random', random_state=0, solver='mu', beta_loss='kullback-leibler')
W = nmf.fit_transform(data_scaled).round(decimals=3) # Customer-factor matrix
H = nmf.components_.round(decimals=3)  # Cuisine-factor matrix

# Create a DataFrame for W, and H with appropriate row and column names
H_df = pd.DataFrame(H, columns=cuisines, index=[f"Factor_{i+1}" for i in range(H.shape[0])])
W_df = pd.DataFrame(W, columns=[f"Factor_{i+1}" for i in range(W.shape[1])], index=data.index)

In [70]:
W_df

    Factor_1  Factor_2  Factor_3  Factor_4  Factor_5
0      0.000     0.569     0.000     0.000     0.000
1      0.587     0.000     0.000     0.000     0.432
2      0.000     0.000     0.234     0.000     0.324
3      0.587     0.095     0.000     0.000     0.000
4      0.000     0.000     0.000     1.466     0.000
5      0.000     0.000     0.000     0.000     1.297
6      0.000     0.000     0.467     0.000     0.000
7      0.000     0.000     0.000     1.257     0.000
8      0.000     0.000     0.000     0.000     1.081
9      0.000     0.000     0.701     0.000     0.000
10     0.000     0.000     0.000     0.522     0.001
11     0.000     0.758     0.000     0.000     0.000
12     0.000     0.847     0.000     0.000     0.008
13     0.000     0.000     0.467     0.000     0.000
14     0.000     0.190     0.701     0.000     0.000
15     0.000     0.000     0.806     0.126     0.000
16     0.000     0.284     0.351     0.000     0.000
17     0.929     0.000     0.000     0.000     0.000
18     0.684     0.000     0.351     0.000     0.000
19     0.000     0.474     0.000     0.419     0.000

In [71]:
H_df

,Italian,American,Chinese,Mexican,Indian,Japanese,French,Thai,Spanish,Mediterranean,Greek,Lebanese,Turkish,Korean,Vietnamese,Persian,Brazilian,Caribbean,Moroccan,Ethiopian
Factor_1,0.179,0.000,0.000,0.718,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.628,0.00,0.000,0.0,0.000,0.179,0.000,0.000,0.0
Factor_2,0.466,0.073,0.000,0.000,0.933,0.000,0.000,0.000,0.000,0.855,0.00,0.000,0.00,0.000,0.0,0.000,0.311,0.000,0.000,0.0
Factor_3,0.000,0.000,1.349,0.000,0.000,0.000,0.000,0.196,0.409,0.000,0.49,0.000,0.00,0.163,0.0,0.000,0.000,0.000,0.245,0.0
Factor_4,0.000,0.000,0.000,0.220,0.000,0.000,0.175,0.317,0.176,0.000,0.00,0.000,0.44,0.264,0.0,0.000,0.000,0.000,0.000,0.0
Factor_5,0.000,0.562,0.000,0.000,0.000,0.636,0.319,0.159,0.000,0.000,0.00,0.000,0.00,0.000,0.0,0.318,0.000,0.318,0.000,0.0

In [100]:
# Top labels for H (cuisine-factor matrix)
top_labels_H = {}
for factor in H_df.index:
    # Sort cuisines for the current factor
    sorted_cuisines = H_df.loc[factor].sort_values(ascending=False)
    top_cuisines = sorted_cuisines.head(3).index.tolist()  # Top 3 cuisines
    top_labels_H[factor] = {"Top Cuisines": top_cuisines}

# Display top cuisines for each factor in H
print("Top Cuisines for Each Factor (H):")
for factor, labels in top_labels_H.items():
    print(f"{factor}:")
    print(f"  Top Cuisines: {', '.join(labels['Top Cuisines'])}")
    print()

# Top labels for W (customer-factor matrix)
top_labels_W = {}
for factor in W_df.columns:
    # Sort customers for the current factor
    sorted_customers = W_df[factor].sort_values(ascending=False)
    top_customers = sorted_customers.head(3).index.tolist()  # Top 3 customers
    top_labels_W[factor] = {"Top Customers": top_customers}

Top Cuisines for Each Factor (H):
Factor_1:
  Top Cuisines: Mexican, Lebanese, Italian

Factor_2:
  Top Cuisines: Indian, Mediterranean, Italian

Factor_3:
  Top Cuisines: Chinese, Greek, Spanish

Factor_4:
  Top Cuisines: Turkish, Thai, Korean

Factor_5:
  Top Cuisines: Japanese, American, French

Top Customers for Each Factor (W):
Factor_1:
  Top Customers: 17, 18, 3

Factor_2:
  Top Customers: 12, 11, 0

Factor_3:
  Top Customers: 15, 14, 9

Factor_4:
  Top Customers: 4, 7, 10

Factor_5:
  Top Customers: 5, 8, 1

# sPCA

In [116]:
import numpy as np
import pandas as pd
from sklearn.decomposition import SparsePCA
from sklearn.preprocessing import StandardScaler

# Assuming you have your dataset stored in 'data'
# Preprocess the data (Standardize it)
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

# Apply Sparse PCA to extract sparse components
n_components = 5  # Number of components you want to extract
sparse_pca = SparsePCA(n_components=n_components, alpha=2, random_state=0)

# Fit the Sparse PCA model
sparse_pca.fit(data_scaled)

# Get the Sparse PCA components
components = sparse_pca.components_

# Get the top labels for Sparse PCA components (top values in each component)
top_labels = {}
for i, component in enumerate(components):
    sorted_indices = np.argsort(component)[::-1]  # Sort in descending order
    top_features = data.columns[sorted_indices][:3]  # Top 3 features
    top_labels[f'Component_{i+1}'] = top_features

# Display top labels for each Sparse PCA component
print("\nTop Labels for Each Sparse PCA Component:")
for component, labels in top_labels.items():
    print(f"{component}: {', '.join(labels)}")
    
# Convert the components into a DataFrame with cuisines as columns and components as rows
components_df = pd.DataFrame(components, columns=data.columns, index=[f"Component_{i+1}" for i in range(components.shape[0])])

# Display the DataFrame
print("\nSparse PCA Components DataFrame:")
components_df.T

Top Labels for Each Sparse PCA Component:
Component_1: Caribbean, French, Japanese
Component_2: Spanish, Moroccan, Ethiopian
Component_3: American, Persian, Ethiopian
Component_4: Italian, Moroccan, American
Component_5: Brazilian, Indian, Ethiopian

Sparse PCA Components DataFrame:

               Component_1  Component_2  Component_3  Component_4  Component_5
Italian           0.000000     0.000000     0.000000          1.0     0.000000
American          0.000000     0.000000     0.707107         -0.0     0.000000
Chinese           0.000000     0.000000     0.000000         -0.0     0.000000
Mexican           0.000000     0.000000     0.000000         -0.0     0.000000
Indian            0.000000     0.000000     0.000000         -0.0     0.706588
Japanese          0.468279     0.000000     0.000000         -0.0     0.000000
French            0.590234     0.000000     0.000000         -0.0     0.000000
Thai              0.000000     0.000000     0.000000         -0.0     0.000000
Spanish           0.000000     0.707107     0.000000         -0.0     0.000000
Mediterranean     0.000000     0.000000     0.000000         -0.0     0.000000
Greek             0.000000     0.000000     0.000000         -0.0     0.000000
Lebanese          0.000000     0.000000     0.000000         -0.0     0.000000
Turkish           0.000000     0.000000     0.000000         -0.0     0.000000
Korean            0.000000     0.000000     0.000000         -0.0     0.000000
Vietnamese        0.000000     0.000000     0.000000         -0.0     0.000000
Persian           0.000000     0.000000     0.707107         -0.0     0.000000
Brazilian         0.000000     0.000000     0.000000         -0.0     0.707626
Caribbean         0.657525     0.000000     0.000000         -0.0     0.000000
Moroccan          0.000000     0.707107     0.000000         -0.0     0.000000
Ethiopian         0.000000     0.000000     0.000000         -0.0     0.000000